# Generated by Django 4.2.16 on 2024-09-10 16:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2, unique=True)),
                ("country_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customer_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_slug", models.SlugField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrackingNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(db_index=True, max_length=16, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracking.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parcel",
            fields=[
                (
                    "parcel_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=3, max_digits=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_country",
                        to="tracking.country",
                    ),
                ),
                (
                    "origin_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="origin_country",
                        to="tracking.country",
                    ),
                ),
                (
                    "tracking_number",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracking.trackingnumber",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_status", models.CharField(default="Pending", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracking.customer",
                    ),
                ),
                (
                    "parcel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracking.parcel",
                    ),
                ),
            ],
        ),
    ]
